### ISSUE TITLE
Callable type of a class in dynamic blocks

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-js#424]
In JS, in a browser, this code of dynamic block does not work :
```ceylon
dynamic x = XMLHttpRequest;
x(); // Runtime ERROR : TypeError: Constructor XMLHttpRequest requires 'new'
```

**Comment by Kurremkarmerruk** [comment]
> Anyway if you directly do XMLHttpRequest() the compiler adds the new to it.

The problem with that is that you need to be able to call the variable to allow for a common JS pattern.

For express:
~~~JavaScript
var express = require('express')
var app = express()
~~~
For Koa.js:
~~~JavaScript
var koa = require('koa');
var app = koa();
~~~
And hapi.js:
~~~JavaScript
var Hapi = require('hapi');
var server = new Hapi.Server();
~~~
*hapi.js can't work at all because the instantiating object is a member of the object returned by require*

Is there a workaround? I want to be able to do this:
~~~Ceylon
//run.ceylon
shared void run() {
	
	Application app;
	
	dynamic {
		dynamic express = require("express");
		app = createApp(express);
		
        ...

	}

	...

}
~~~
~~~Ceylon
//express.ceylon
dynamic Application {
	
	shared formal void get(String path, 
		Anything(Request, Response)|Null|Anything(Request, Response)[] callbacks=null);
	
	shared formal Server listen(Integer port, Anything() callable);

	...

}

Application createApp(dynamic express) {
	dynamic { return express(); }
}
~~~
as that is how one could create a Ceylon interface for *any* node module.  I see this as a really great way to get people excited about Ceylon i.e., getting excited about using simple and powerful node modules within the strongly-typed Ceylon language and powerfully-featured Ceylon IDE.

**Comment by sgalles** [comment]
@Kurremkarmerruk Yes there's a workaround. You must try to attach the `Hapi.Server` object on a global object of your JS envirronment.
I didn't try this on NodeJS but you can try something like this
```ceylon
var Hapi = require('hapi');
global.\iHapiServer = Hapi.\iServer;
var server = HapiServer();
```
I did something like this in the browser for the threejs library https://github.com/sgalles/ceylon-webgl/blob/master/source/ceylonjs/webgl/three/contract.ceylon
```ceylon
shared Scene scene(){
 Scene scene;
 dynamic {
  window.\iDynTreeScene = THREE.\iScene;
  scene = DynTreeScene();
 }
 return scene;
}
```

**Comment by gavinking** [comment]
Why doesn't something like `value server = \iHapi.Server()` work?

**Comment by sgalles** [comment]
Because of https://github.com/ceylon/ceylon-js/issues/441

**Comment by gavinking** [comment]
Well #441 talks about making. `Hapi.Server()` work. That's not what I just wrote. I wrote `\iHapi.Server()`, to force the interpretation of `Hapi` as a value.

**Comment by sgalles** [comment]
IIRC it does not work. But I'll try this out tonight though.

**Comment by Kurremkarmerruk** [comment]
@gavinking trying that, I get this error:
~~~
ion("Undefined or null reference: Hapi"),'49:19-49:22','run.ceylon'):Hapi).();
                                                                           ^
SyntaxError: Unexpected token (
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at [eval]:1:85
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:536:25)
~~~
and the `Server` attribute is annotated with this error:
~~~
GenerateJsVisitor caused an exception visiting QualifiedTypeExpression node: java.lang.NullPointerException at unknown
~~~

**Comment by gavinking** [comment]
OK, so @chochos would you please fix that NPE for us?

**Comment by gavinking** [comment]
Actually, @Kurremkarmerruk would you please report the NPE as a separate issue, since it doesn't really belong here. Thanks.

**Comment by sgalles** [comment]
> Why doesn't something like value server = \iHapi.Server() work?

@gavinking I've removed my workaround with the global object and I tried 
```ceylon
Scene scene;
dynamic {
   scene = \iTHREE.Scene();
}
```
But I get
```
Uncaught TypeError: Cannot read property '$$' of undefined
```
So for me, https://github.com/ceylon/ceylon-js/issues/441 also included this problem.

**Comment by chochos** [comment]
I don't see why the need for the capital H. We simply should make this work:

````ceylon
dynamic {
  dynamic hapi=require("hapi");
  dynamic server=hapi.Server();
}
````

By turning it into `new $bla.Server()` instead of simply `$bla.Server()`.

So basically @Kurremkarmerruk this is the same as #441

**Comment by chochos** [comment]
Typechecker now supports this (and the compiler already did for some time now).
