### ISSUE TITLE
Add test to test the distrib samples

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-js#430]
Compile, run.

**Comment by chochos** [comment]
I reviewed the samples, and it seems we'd need to specify which ones to compile. `helloworld`, `no-module` and `with-module` seem redundant given that we compile the language module tests which are in the default module (same as `no-module`) and a bunch of other modules (same as `with-module`). In any case the only interesting thing would be to compile `plugin` and `interop-java`, to get the expected error (but this requires that we _expect_ the error, which is not part of the current tests).

**Comment by quintesse** [comment]
I don't think this is meant to test language features, like you say there are more than enough of those already. I'm pretty sure the reason for this issue is to make sure that the examples themselves actually work. They will be one of the first things many people new to Ceylon will try it it would look really bad if we make a distribution where the examples fail.
(FYI, we've been testing all the examples manually in all the previous releases)

**Comment by chochos** [comment]
ok but then we could add a global ant file to compile and run all samples, right? that's something to be done in that repo, not include it in the js tests

**Comment by quintesse** [comment]
Well we have ant files for that, but if people forget to run them they don't help, that's why it was decided to include them in the tests, so they get run each time the tests are run.

**Comment by FroMage** [comment]
Done.
