### ISSUE TITLE
Binary version mismatch is reported on wrong module

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon-js#494]
If I import `ceylon.collection "1.1.0"`, and try to compile that with the current compiler, I get:

> ceylon compile-js: The Ceylon-JS module ceylon.language has binary version 7.0
is incompatible with the compiler version 8.0

The error message should mention `ceylon.collection` instead.

**Comment by jvasileff** [comment]
As mentioned in #490:

> 1.1.0 modules pull in the 1.1.0 language module

This is also discussed towards the end of #483.

Given that the language module is an implicit `shared` import, would it make sense to add (not bypass?) a language module version check too, and not rely solely on binary compatibility? A side effect may be better error messages.

In other words, even if 1.1.1 had binary compatibility with 1.1.0, the import should be disallowed, since, for instance (if I understand correctly) `Iterable`s created with language module 1.1.0 would be missing the new `each` method.

I posted to the user list prior to #490 about not being able to import 1.1.0 modules when using dev builds. Perhaps the problems I saw were related to language module incompatibilities. There were some very strange errors - I think one had to do with `runtime.maxArraySize`, but most actually showed up as type checker errors.

**Comment by chochos** [comment]
Any newly compiled modules will use the 1.1.1 language module; the 1.1.0 language module will be used only by modules compiled with the old compiler. And yes, objects created in the older language module will only have the members defined in that module; if passed to code expecting new members added in 1.1.1 there will be runtime errors.

I think @quintesse mentioned somewhere that in JVM they have some way of always loading the latest language module. This can be achieved using an alias of some sort (a symlink named `latest` for instance). The problem here is, even if I implement this now, modules compiled with 1.1.0 will still refer to the 1.1.0 language module.

**Comment by quintesse** [comment]
Well we hard-code it in the compiler, removing any reference to `ceylon.language` before generating the code for `module.ceylon`. You could just do the opposite in your module loading code: whenever you encounter a dependency on `ceylon.language/X.Y` you just replace it with the correct version. (You might do a sanity check of course and only exchange `1.1.0` with `1.1.1`).

**Comment by quintesse** [comment]
NB: personally I would have preferred to do that in the JVM version as well (compìle the information but override at runtime), right now we don't really know for sure with which version of the language module things were compiled, except by assuming that for each binary version there's exactly one language module version, which most likely won't always be true.

**Comment by chochos** [comment]
@quintesse replacing the 1.1.0 with 1.1.1 for the language module will certainly fix this compilation problem (which is the original issue anyway), but not the fact that objects created with the older language module might fail when passed to code that expects objects from the new language module.

**Comment by chochos** [comment]
@lucaswerkmeister please test again, you should be able to compile with `ceylon.collection/1.1.0`

**Comment by quintesse** [comment]
> objects created with the older language module

What objects? There wouldn't be an older language module, only the new one, right?

**Comment by chochos** [comment]
It's like this:

`mynewlycompiledmodulewith111/1.0` calls `ceylon.collection/1.0.0` which uses `ceylon.language/1.0.0` to create, say, an `Iterable`. That `Iterable` is passed to the code in `mynewlycompiledmodulewith111` which itself uses `ceylon.language/1.1.1`, where `Iterable` has some new methods (I think `each` was mentioned). But this `Iterable` doesn't have the `each` method because it was created with an older language module (and because of the way objects and prototypes and modules work in JS). So when `each` is called in that `Iterable`, fecal matter hits the horizontal wind pusher.

**Comment by quintesse** [comment]
Ok, but I don't think `ceylon.collection/1.0.0` shouldn't be using `ceylon.language/1.0.0` either, you have to upgrade *all* occurrences of `ceylon.language/1.0.0` to `ceylon.language/1.1.0`. In fact, unless you also have Ceylon 1.0.0 installed I don't even know where the old `ceylon.language/1.0.0` would come from.

**Comment by chochos** [comment]
Well `ceylon.collection/1.0.0` is indeed using `ceylon.language/1.0.0` - it will fetch it from the CMR if it has to (if `run-js` was used, of course; in web apps there's no such thing).

**Comment by quintesse** [comment]
But I don't think it should, the `ceylon.language` should never be downloaded because you should have it installed. And that version is the only one that should be used at runtime.
So as long as your loader ignores any reference to `ceylon.language/X.Y.Z` and just always uses the version installed with the runtime things should work. Right?

**Comment by chochos** [comment]
But in JS there's no way to say "oh just load the newest version whatever that is", that's why the modules must have a reference to the language module with which they were compiled.

**Comment by quintesse** [comment]
There's no way to "pre-register" a certain name but have it point to a different module, like we can do for example with RequireJS in a website?

**Comment by lucaswerkmeister** [comment]
> @lucaswerkmeister please test again, you should be able to compile with ceylon.collection/1.1.0

@chochos yup, that works now, thanks

**Comment by chochos** [comment]
so can we close this issue then?

**Comment by chochos** [comment]
@quintesse that works in requireJS but not with node's `require`

**Comment by quintesse** [comment]
We could probably override node's `require()` with out own that checks if the name is `ceylon.language` and then change it to the needed version before passing it on the the actual `require()`, right? I mean, we need to come up with some kind of solution that works the same way for both the JVM and the JS side.

**Comment by chochos** [comment]
We'd need to implement our own require somewhere in a separate module and import that one before anything else. I don't know how that implementation would work though... I mean, what version of the language module should it load? Wouldn't we just be passing the versioning to this new module? Then if someone uses an older version of that module, they'll get an older language module.

**Comment by quintesse** [comment]
Our own require? No I just mean something like (pseudocode):

```
var oldRequire=require;
require=function(mod) {
    if (mod.contains("ceylon.language")) {
        return require("ceylon.language/1.1.1");
    } else {
        return oldRequire(nm);
    }
}
```

**Comment by chochos** [comment]
There's something strange going on with node's `require` that won't let you do that (or was it `requirejs`? can't remember, but you can't have a function named `require`). You can create your own `require` and name it something else obviously...

**Comment by chochos** [comment]
But anyway, my question remains: where do we put this function? It must be in a separate module. Something that you call _before_ importing the language module.

**Comment by quintesse** [comment]
I just tested it and it seems to work just fine on NodeJS, maybe in some other, more complex, situation.

We put it where you put the rest of your init code, in `CeylonRunJsTool`: https://github.com/ceylon/ceylon-js/blob/master/src/main/java/com/redhat/ceylon/compiler/js/CeylonRunJsTool.java#L311

**Comment by chochos** [comment]
OK so this is the reason why this fails, and I don't know if this is still valid:

Except for the language module, we allow modules compiled with 1.1.1 to load modules compiled with 1.1.0. That's why the error complains about `ceylon.language`. 

So the real problem here is what @quintesse had mentioned about the language module, about how any modules that can be run should use the latest language module.

But since `SearchableList` and other stuff has made 1.1.1 (or 1.2 or whatever) incompatible with 1.1.0, this is moot.
