### ISSUE TITLE
Strange type error in dynamic block

### ISSUE THREAD

**Issue by dhoehmann** [ceylon/ceylon-js#616]
This is a quite weird behaviour with version 1.1 - don't know if this is still the case in 1.2.
The code below contains two functions that should do the same. But one of them has an unneeded type check - and works. The other doesn't have the check and fails with a type error

```Ceylon
dynamic Str {
}

T createStr<T>() {
	if (`T`.exactly(`Nothing`)) {
		throw Exception();
	} else {
		dynamic {
			return eval("new String()");
		}
	}
}

T newStr<T>() {
	dynamic {
		return eval("new String()");
	}
}

void run() {
	print("Trying createStr");
	print(createStr<Str>());
	print("success. Now trying newStr");
	print(newStr<Str>());
	print("success!");
}
run();
```

When executed in Web Runner this gives me:
```
Trying createStr

success. Now trying newStr
Runtime error:
--- TypeError: Expected T (SCRIPT.ceylon 18:9-18:28)
```

**Comment by lucaswerkmeister** [comment]
Can confirm, getting the same here:
> Trying createStr
> 
> success. Now trying newStr
> /home/lucas/git/ceylon/ceylon-dist/dist/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:800
>       ^
> TypeError: Expected tmp::Str (run.ceylon 16:19-16:38)
>     at Object.ndtc$ (/home/lucas/git/ceylon/ceylon-dist/dist/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:800:7)
>     at newStr (/run/media/lucas/Windows/Users/Lucas/workspace/tmp/modules/tmp/1.0.0/tmp-1.0.0.js:30:12)
>     at run (/run/media/lucas/Windows/Users/Lucas/workspace/tmp/modules/tmp/1.0.0/tmp-1.0.0.js:36:11)
>     at [eval]:1:273
>     at Object.exports.runInThisContext (vm.js:74:17)
>     at Object.<anonymous> ([eval]-wrapper:6:22)
>     at Module._compile (module.js:460:26)
>     at evalScript (node.js:431:25)
>     at startup (node.js:90:7)
>     at node.js:814:3

**Comment by chochos** [comment]
Huh, guess I never thought of testing the use of a dynamic interface as a type parameter.

**Comment by dhoehmann** [comment]
And then despicable me come around and use it ... ;-)

**Comment by chochos** [comment]
Actually, I think this is not a bug. `newStr<Str>` should return a `Str` and it's returning a native `String`. Since the function is not native, the return value will leave the `dynamic` scope; a check is performed to make sure the returned value is indeed a `Str` and it's not.

The real question is, why does the first function work? It should throw as well...

**Comment by chochos** [comment]
something to do with scope apparently.

**Comment by dhoehmann** [comment]
I've only used String for the simplified example. In my code an OpenUI5 object is created and returned.
A real piece of code is this:

```Ceylon
shared dynamic Sap_ui_table_Column satisfies Sap_ui_core_Element {
	formal shared Sap_ui_table_Column setLabel(Sap_ui_core_Control | String label);
	formal shared Sap_ui_table_Column setTemplate(Sap_ui_core_Control | String label);
}
shared T createOpenUIElement<T>() given T satisfies Sap_ui_base_Object {
	if (`T`.exactly(`Nothing`)) { //This is completely weird - but ceylon throws a type error if we omit this check
		throw Exception();
	} else {
		value name = `T`.string.replaceFirst("Sap", "sap").replace("_", ".").split(':'.equals).last else "";
		dynamic {
			return eval("new "+name+"()");
		}
	}
}
```
As I understood JS interop this should work ?!

**Comment by chochos** [comment]
Ah, this is a case I hadn't thought of before.

When the return type is a dynamic interface, a different check is used: one that dresses up the returned object with the type information of the dynamic interface _if_ it really adheres to it. But in this case, since the return type is a type parameter, we can't know at compile time if the type argument is going to be a dynamic interface. At least in the original example; in this latest example, there's a type constraint so we could use that to determine what check to use.
