### ISSUE TITLE
bloat in ceylon.language-1.2.0.js

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-js#662]
I just scanned the source of the generated js for the language module and to my suprise there is:

- 37 `by()` annotations
- 126 `tagged()` annotations
- 190 `doc()` annotations
- 180 `see()` annotations

All carrying around strings and other garbage.

I don't think they should be there.

**Comment by chochos** [comment]
The `doc` annotations with strings are only for short strings, where the reference to the string in the model would be longer than just including the literal (look for `doc$` calls in the JS code; those are calls to retrieve the `doc` string from the JSON model).

As for the rest, I can simply omit them from the runtime metamodel, *if* that's the way it also works in JVM. I left all (or at least some of) these because there are tests that retrieve runtime info for these annotations.

**Comment by chochos** [comment]
I supposed we can do away with `throws` as well

**Comment by chochos** [comment]
Removing `by`, `see`, `doc`, `tagged` and `throws` annotations from the runtime metamodel makes the resulting JS file 33KB smaller.

**Comment by gavinking** [comment]
OK, fine so that doesn't seem worth it. Fine.
